[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[theme]
base = "dark"
primaryColor = "#0040ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2130"
textColor = "#fafafa"
font = "sans serif"
